name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Хелоу мазафакер! Велкам ту ауэ тим ёпта! Сделаем аниме ещё лучшим дерьмом!"
        pr-message: "Ты красавчик епта! С первым пул реквестом во имя гребаног оаниме, мать его!"
    - name: CodeThreat Scanner
      uses: CodeThreat/codethreat-github-action@v1.023
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v3.1.0
      with:
        projectBaseDir: "anime_enhancement"
    
